name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
            
      - name: Checkout `simulation`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/simulation
          token: ${{ secrets.PAT }}
          path: simulation
      
      - name: Checkout `text-rendering`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/text-rendering
          token: ${{ secrets.PAT }}
          path: text-rendering
      
      - name: Checkout `freetype`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/freetype
          token: ${{ secrets.PAT }}
          path: freetype
      
      - name: Checkout `data`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/data
          token: ${{ secrets.PAT }}
          path: data
      
      - name: Checkout `unmanaged`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged
      
      - name: Checkout `font-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/font-systems
          token: ${{ secrets.PAT }}
          path: font-systems
      
      - name: Checkout `data-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/data-systems
          token: ${{ secrets.PAT }}
          path: data-systems
      
      - name: Checkout `collections`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/collections
          token: ${{ secrets.PAT }}
          path: collections
      
      - name: Checkout `worlds`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/worlds
          token: ${{ secrets.PAT }}
          path: worlds
      
      - name: Checkout `fonts`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/fonts
          token: ${{ secrets.PAT }}
          path: fonts
      
      - name: Checkout `types`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/types
          token: ${{ secrets.PAT }}
          path: types
      
      - name: Checkout `textures`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/textures
          token: ${{ secrets.PAT }}
          path: textures
      
      - name: Checkout `rendering`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/rendering
          token: ${{ secrets.PAT }}
          path: rendering
      
      - name: Checkout `bin-packer`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/bin-packer
          token: ${{ secrets.PAT }}
          path: bin-packer
      
      - name: Checkout `shaders`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/shaders
          token: ${{ secrets.PAT }}
          path: shaders
      
      - name: Checkout `meshes`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/meshes
          token: ${{ secrets.PAT }}
          path: meshes
      
      - name: Checkout `materials`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/materials
          token: ${{ secrets.PAT }}
          path: materials
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            
      - name: Build `TextRendering.Systems`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Debug /p:Version=${VERSION}
      
      - name: Build `TextRendering.Systems`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION}
      
      - name: Build `TextRendering.Systems.Tests`
        run: dotnet build "${{ github.event.repository.name }}/tests" -c Debug /p:Version=${VERSION}
      
      - name: Build `TextRendering.Systems.Tests`
        run: dotnet build "${{ github.event.repository.name }}/tests" -c Release /p:Version=${VERSION}
            
      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Release --logger "trx"
            
      - name: Pack `TextRendering.Systems`
        run: dotnet pack "${{ github.event.repository.name }}/source" /p:Version=${VERSION} --no-build --output .

      - name: Add NuGet Source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
            
      - name: Publish `TextRendering.Systems`
        run: dotnet nuget push TextRendering.Systems.${VERSION}.nupkg --source github --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}